/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import shared.Global;
import java.util.List;
import models.Favorito;
import services.FavoritoService;

/**
 *
 * @author Tiago Enriquez Tachy
 */
public class Atualizacao extends javax.swing.JFrame {
    
    Principal principal;
    Favorito favorito;
    FavoritoService favoritoService;

    /**
     * Inicializa tela de Atualização de favorito com as informações da tela principal e do favorito.
     * @param principal
     * @param favorito
     */
    public Atualizacao(Principal principal, Favorito favorito) {
        initComponents();
        this.logo();
        setLocationRelativeTo(this);
        this.principal = principal;
        this.favorito = favorito;
        this.favoritoService = new FavoritoService();
        preencherCampos(favorito);
        preencherAssuntos();
        selecionarAssunto(favorito);
    }

    /**
     * Creates new form Atualizacao
     */
    public Atualizacao() {
        initComponents();
    }
    
    /**
     * Preenche os campos de digitação.
     * @param favorito 
     */
    private void preencherCampos(Favorito favorito) {
        Integer id = favorito.getId();
        textFieldId.setText(id.toString());
        textFieldNome.setText(favorito.getNome());
        textFieldUrl.setText(favorito.getUrl());
        textFieldAssunto.setText(favorito.getAssunto());
    }

    /**
     * Preenche o combo box com os assuntos dos favoritos.
     */
    private void preencherAssuntos() {
        try {
            List<String> assuntos = favoritoService.assuntos();
            comboBoxAssuntos.addItem("");
            assuntos.forEach((assunto) -> {
                comboBoxAssuntos.addItem(assunto);
            });
        } catch (Exception exception) {
            new Erro(exception.getMessage()).setVisible(true);
        }
    }
    
    /**
     * Seleciona o assunto do favorito.
     * @param favorito 
     */
    private void selecionarAssunto(Favorito favorito) {
        comboBoxAssuntos.setSelectedItem(favorito.getAssunto());
    }
    
    /**
     * Fecha esta janela informando isso para a tela principal.
     */
    private void fechar() {
        principal.fecharAlteracao();
        this.dispose();
    }
    
    /**
     * Mostra logotipo.
     */
    private void logo() {
        try {
            new Global().logo(this);
        } catch (Exception exception) {
            new Erro("Erro ao mostrar o logotipo").setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        textFieldNome = new javax.swing.JTextField();
        textFieldUrl = new javax.swing.JTextField();
        textFieldAssunto = new javax.swing.JTextField();
        comboBoxAssuntos = new javax.swing.JComboBox<>();
        buttonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização de favorito");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Id");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Nome");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("URL");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 30));
        jLabel3.setRequestFocusEnabled(false);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Assunto");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 30));

        textFieldId.setDisabledTextColor(new java.awt.Color(64, 64, 64));
        textFieldId.setEnabled(false);
        textFieldId.setPreferredSize(new java.awt.Dimension(300, 30));

        textFieldNome.setPreferredSize(new java.awt.Dimension(300, 30));

        textFieldUrl.setPreferredSize(new java.awt.Dimension(300, 30));

        textFieldAssunto.setPreferredSize(new java.awt.Dimension(300, 30));

        comboBoxAssuntos.setPreferredSize(new java.awt.Dimension(300, 30));
        comboBoxAssuntos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                escolherAssunto(evt);
            }
        });

        buttonAlterar.setBackground(new java.awt.Color(0, 0, 0));
        buttonAlterar.setForeground(new java.awt.Color(255, 255, 0));
        buttonAlterar.setText("Salvar alteração");
        buttonAlterar.setPreferredSize(new java.awt.Dimension(130, 30));
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxAssuntos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldAssunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(comboBoxAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Informa a tela principal que esta tela está sendo fechada.
     * @param evt 
     */
    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
        fechar();
    }//GEN-LAST:event_fechar

    /**
     * Insere no campo de digitação do assunto o escolhido no combo box.
     *
     * @param evt
     */
    private void escolherAssunto(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_escolherAssunto
        String assunto = comboBoxAssuntos.getSelectedItem().toString();
        textFieldAssunto.setText(assunto);
    }//GEN-LAST:event_escolherAssunto

    /**
     * Salva as alterações dos dados de um favorito.
     * @param evt 
     */
    private void alterar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar
        try {
            int id = Integer.parseInt(textFieldId.getText());
            String nome = textFieldNome.getText();
            String url = textFieldUrl.getText();
            String assunto = textFieldAssunto.getText();
            favoritoService.alterar(new Favorito(id, nome, url, assunto));
            principal.preencherListas();
            new Sucesso("Alterações salvas com sucesso").setVisible(true);
            fechar();
        } catch (Exception exception) {
            new Erro("Erro ao salvar as alterações\n" + exception.getMessage()).setVisible(true);
        }
    }//GEN-LAST:event_alterar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atualizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JComboBox<String> comboBoxAssuntos;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldAssunto;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldUrl;
    // End of variables declaration//GEN-END:variables

}
