/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import shared.Global;
import models.Favorito;
import services.FavoritoService;

/**
 *
 * @author Tiago Enriquez Tachy
 */
public class Remocao extends javax.swing.JFrame {
    
    Principal principal;
    Favorito favorito;
    FavoritoService favoritoService;

    /**
     * Inicializa a tela de remoção de favorito com as informações da tela principal e do favorito.
     * @param principal
     * @param favorito
     */
    public Remocao(Principal principal, Favorito favorito) {
        this.principal = principal;
        this.favorito = favorito;
        this.favoritoService = new FavoritoService();
        initComponents();
        this.logo();
        setLocationRelativeTo(this);
        textAreaPergunta.setText(""
                + "Deseja de fato remover o seguinte favorito?\n"
                + "Id: " + favorito.getId() + "\n"
                + "Nome: " + favorito.getNome() + "\n"
                + "URL: " + favorito.getUrl() + "\n"
                + "Assunto: " + favorito.getAssunto()
        );
    }
    
    /**
     * Mostra logotipo.
     */
    private void logo() {
        try {
            new Global().logo(this);
        } catch (Exception exception) {
            new Erro("Erro ao mostrar o logotipo").setVisible(true);
        }
    }

    /**
     * Creates new form Remocao
     */
    public Remocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPergunta = new javax.swing.JTextArea();
        buttonSim = new javax.swing.JButton();
        buttonNao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remoção de favorito");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        textAreaPergunta.setColumns(20);
        textAreaPergunta.setRows(5);
        textAreaPergunta.setPreferredSize(new java.awt.Dimension(200, 120));
        jScrollPane1.setViewportView(textAreaPergunta);

        buttonSim.setBackground(new java.awt.Color(0, 0, 0));
        buttonSim.setForeground(new java.awt.Color(255, 255, 0));
        buttonSim.setText("Sim");
        buttonSim.setPreferredSize(new java.awt.Dimension(60, 30));
        buttonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deletar(evt);
            }
        });

        buttonNao.setBackground(new java.awt.Color(0, 0, 0));
        buttonNao.setForeground(new java.awt.Color(255, 255, 0));
        buttonNao.setText("Não");
        buttonNao.setPreferredSize(new java.awt.Dimension(60, 30));
        buttonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desistir(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Informa a tela principal que esta tela está sendo fechada.
     * @param evt 
     */
    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
        principal.fecharRemocao();
    }//GEN-LAST:event_fechar

    /**
     * Remove o favorito do banco de dados.
     * @param evt 
     */
    private void Deletar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deletar
        try {
            favoritoService.deletar(favorito.getId());
            principal.preencherListas();
            new Sucesso("Favorito removido com sucesso.").setVisible(true);
            this.dispose();
        } catch (Exception exception) {
            new Erro("Não foi possível excluir o favorito.\n" + exception.getMessage()).setVisible(true);
            System.out.println(exception);
        }
    }//GEN-LAST:event_Deletar

    private void Desistir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desistir
        this.dispose();
    }//GEN-LAST:event_Desistir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNao;
    private javax.swing.JButton buttonSim;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaPergunta;
    // End of variables declaration//GEN-END:variables

}
